<a href="https://colab.research.google.com/github/Abhishek-Dutta/pytorch-learning/blob/main/learn-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
x = torch.empty(2,2,2)
print(x)

tensor([[[-3.5224e-31,  4.3735e-41],
         [-3.5224e-31,  4.3735e-41]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [7]:
y = torch.rand(2,2)
print(y)

tensor([[0.2798, 0.4789],
        [0.3446, 0.7463]])


In [8]:
x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [10]:
x = torch.zeros(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [12]:
x = torch.ones(2,2, dtype=torch.float16)
print(x.dtype)
print(x.size())

torch.float16
torch.Size([2, 2])


In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y

print(x, y, z)

y.add_(x)
print(y)

tensor([[0.4440, 0.3907],
        [0.9156, 0.8229]]) tensor([[0.4548, 0.4359],
        [0.6096, 0.5867]]) tensor([[0.8988, 0.8266],
        [1.5252, 1.4097]])
tensor([[0.8988, 0.8266],
        [1.5252, 1.4097]])
